{% set name = "cuda-api-wrappers" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eyalroz/cuda-api-wrappers/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16c68e450e553d2839f00503a44e85b32c4f4e08f154e9f7c85f706bc5c79bf3

build:
  number: 0
  skip: true  # [cuda_compiler_version == 'None']

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja

test:
  commands:
    - test -f ${PREFIX}/include/cuda/api.hpp
    - test -f ${PREFIX}/include/cuda/rtc.hpp
    - test -f ${PREFIX}/include/cuda/nvtx.hpp
    - test -f ${PREFIX}/include/cuda/runtime_api.hpp
    - test -f ${PREFIX}/lib/cmake/cuda-api-wrappers/cuda-api-wrappers-config.cmake
    - test -f ${PREFIX}/lib/cmake/cuda-api-wrappers/cuda-api-wrappers-targets.cmake

about:
  home: https://github.com/eyalroz/cuda-api-wrappers
  summary: Thin, unified, C++-flavored wrappers for the CUDA APIs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://codedocs.xyz/eyalroz/cuda-api-wrappers/
  dev_url: https://github.com/eyalroz/cuda-api-wrappers

extra:
  recipe-maintainers:
    - awvwgk
